#!/bin/sh
# chkconfig: 35 85 99

set -e


start(){
    yum -y update python-boto

    FQDN="FDQN_HERE"
    export AWS_ACCESS_ID="AWS_ACCESS_ID_HERE"
    export AWS_SECRET_KEY="AWS_SECRET_KEY_HERE"


    ec2_hostname=`curl -s http://169.254.169.254/latest/meta-data/public-hostname`.

    update_host.py $FQDN -c $ec2_hostname -t 60
    echo "Set cname $ec2_hostname for $FQDN"

    sed -i "s/#replSet=replicaSetName/replSet=test/" /etc/mongod.conf
}

RETVAL=0

case "$1" in
  start)
    start
    ;;
  *)
    echo "Usage: $0 {start|stop|status|restart|reload|force-reload|condrestart}"
    RETVAL=1
esac
